---
# Template created with Packer or manually
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_debian13

# vCenter Template name
vm_template: catapult-template-debian13

# AWS EC2 Image using owner ID & string lookup because machine IDs are different between regions
ami_owner_id: "136693071363"
ami_name_search_string: debian-13-*
aws_vm_size: t3.small

# Linode Image curl https://api.linode.com/v4/images | jq
linode_image: linode/debian13

# Google Cloud
google_cloud_machine_type: e2-medium # Default when creating manually
google_cloud_vm_image: # Values used to lookup the latest image name for the OS
  path: projects/debian-cloud/global/images
  name: debian-13-trixie
  project: debian-cloud

# Orchard image
orchard_vm_image: ghcr.io/cirruslabs/debian:trixie
