---
# Template created with packer
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_kali2023_3

vm_template: "{{ kali2023_3_vm_template_name | default('catapult-template-kali2023-3') }}"
