---
# Accounts
admin_account: root
template_username: "{{ admin_account }}"

# Connection
ansible_python_interpreter: /usr/bin/python3
default_connection_plugin: ssh
default_ansible_shell_type: sh

# Become
default_ansible_become: true
default_ansible_become_user: "{{ admin_account }}"
