---
# Accounts
admin_account: root
template_username: "{{ admin_account }}"
azure_template_username: azadmin # Azure Does not allow using the admin_account value

# Connection
default_connection_plugin: ssh
default_ansible_shell_type: sh

# Become
default_ansible_become: true
default_ansible_become_user: "{{ admin_account }}"
