---
# Accounts
admin_account: root
template_username: "{{ admin_account }}"

# Connection
customization_method: macos
default_connection_plugin: ssh
default_ansible_shell_type: sh

# Become
default_ansible_become: true
default_ansible_become_user: "{{ admin_account }}"

# Defined here because MacOS does not have Python installed by default so it cannot gather facts
macos_no_python: true
ansible_system: Darwin
