---
# Template created with Packer or manually
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_macos

vm_template: catapult-template-macos

# Accounts
admin_account: root
template_username: "{{ admin_account }}"

# Network
customization_method: macos

# Orchard image
orchard_vm_image: ghcr.io/cirruslabs/macos-tahoe-base:latest
orchard_template_username: admin
orchard_template_password: admin # Default value that comes with the pre-built images
