---
# Accounts
admin_account: root
template_username: "{{ admin_account }}"

# Network
ansible_network_os: opnsense # Not natively supported by Ansible but Catapult can use it to determine the correct tasks to run
customization_method: opnsense
ansible_connection: ansible.builtin.ssh
