---
# Accounts
admin_account: admin
template_username: "{{ admin_account }}"

# Network
ansible_network_os: pfsense # Not natively supported by Ansible but Catapult can use it to determine the correct tasks to run
customization_method: pfsense
ansible_connection: ansible.builtin.ssh
