---
# Template created with packer
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_ubuntu_desktop2404

# vCenter Template name
vm_template: catapult-template-ubuntu-desktop2404

netplan_renderer: NetworkManager
