---
# Template created with packer
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_win81_x86

vm_template: "{{ template_win81_x86_vm_template_name | default('catapult-template-win81-x86') }}"
