---
post_scripts_folder_on_target: c:\tmp # Folder where Ansible will upload files if required

# Accounts
admin_account: Administrator
template_username: "{{ admin_account }}"

# Network
customization_method: windows_cli

# Connection
default_connection_plugin: ssh
default_ansible_shell_type: powershell
ansible_shell_type: "{{ default_ansible_shell_type }}"

# Become
default_ansible_become: false
