---
# Template created with packer
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_winserver2016_gui

vm_template: "{{ winserver2016_gui_vm_template_name | default('catapult-template-winserver2016-gui') }}"
