---
# This is an example file how to extend Catault with your own personal docker-compose-personal.yml file.
# It has the highest priority and will overwrite matching settings from docker-compose.yml & docker-compose-extra.yml.

name: ${CONTAINER_PROJECT_NAME}
services:
  catapult:
    environment:
      EXTRA_PERSONAL: EXAMPLE_PERSONAL
