---
roles:
  - name: geerlingguy.composer
    version: 1.9.2
  - name: geerlingguy.mysql
    version: 4.3.0
  - name: geerlingguy.php
    version: 4.8.0
  - name: geerlingguy.php-versions
    version: 5.0.1
  - name: geerlingguy.postgresql
    version: 3.4.2

collections:
  - name: amazon.aws
    version: 6.3.0
  - name: ansible.netcommon
    version: 5.1.2
  - name: ansible.posix
    version: 1.5.2
  - name: ansible.utils
    version: 2.10.3
  - name: ansible.windows
    version: 1.13.0
  - name: azure.azcollection
    version: 1.14.0
  - name: chocolatey.chocolatey
    version: 1.5.1
  - name: cloud.common
    version: 2.1.2
  - name: community.aws
    version: 6.2.0
  - name: community.crypto
    version: 2.14.1
  - name: community.docker
    version: 3.4.8
  - name: community.general
    version: 7.3.0
  - name: community.hashi_vault
    version: 5.0.0
  - name: community.mysql
    version: 3.7.2
  - name: community.network
    version: 5.0.0
  - name: community.postgresql
    version: 2.4.1
  - name: community.routeros
    version: 2.8.3
  - name: community.vmware
    version: 3.3.0
  - name: community.windows
    version: 2.0.0
  - name: kubernetes.core
    version: 2.4.0
  - name: linode.cloud
    version: 0.18.3
  - name: microsoft.ad
    version: 1.3.0
  - name: microsoft.sql
    version: 2.0.2
  - name: vmware.vmware_rest
    version: 2.2.0
  - name: vyos.vyos
    version: 4.0.0
  - name: https://github.com/vmware/ansible-for-nsxt.git
    type: git
    version: HEAD
