---
# List of default roles and collections that are built into the Catapult image
# If you want to use something else you can use the following module to install them during deployment:
# https://docs.ansible.com/ansible/latest/collections/community/general/ansible_galaxy_install_module.html

roles: []

collections:
  - name: amazon.aws
    version: 9.5.0
  - name: ansible.netcommon
    version: 8.0.0
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 6.0.0
  - name: ansible.windows
    version: 3.0.0
  - name: azure.azcollection
    version: 3.3.1
  - name: chocolatey.chocolatey
    version: 1.5.3
  - name: cisco.ios
    version: 10.0.0
  - name: cloud.common
    version: 3.0.0
  - name: community.aws
    version: 9.3.0
  - name: community.crypto
    version: 2.26.1
  - name: community.docker
    version: 4.6.0
  - name: community.general
    version: 10.6.0
  - name: community.hashi_vault
    version: 6.2.0
  - name: community.library_inventory_filtering_v1
    version: 1.1.1
  - name: community.mysql
    version: 3.13.0
  - name: community.postgresql
    version: 4.0.0
  - name: community.routeros
    version: 3.6.0
  - name: community.vmware
    version: 4.4.0
  - name: community.windows
    version: 3.0.0
  - name: fortinet.fortios
    version: 2.3.9
  - name: kubernetes.core
    version: 5.1.0
  - name: linode.cloud
    version: 0.37.1
  - name: microsoft.ad
    version: 1.9.0
  - name: microsoft.sql
    version: 2.2.3
  - name: paloaltonetworks.panos
    version: 2.21.4
  - name: vmware.vmware_rest
    version: 4.7.0
  - name: vmware.vmware
    version: 2.0.0
  - name: vyos.vyos
    version: 5.0.0
  - name: https://github.com/vmware/ansible-for-nsxt.git
    type: git
