---
# List of default roles and collections that are built into the Catapult image
# If you want to use something else you can use the following module to install them during deployment:
# https://docs.ansible.com/ansible/latest/collections/community/general/ansible_galaxy_install_module.html

roles: []

collections:
  - name: amazon.aws
    version: 10.1.2
  - name: ansible.netcommon
    version: 8.2.0
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: ansible.windows
    version: 3.2.0
  - name: azure.azcollection
    version: 3.8.0
  - name: chocolatey.chocolatey
    version: 1.5.3
  - name: cisco.ios
    version: 11.1.1
  - name: cloud.common
    version: 3.0.0
  - name: community.aws
    version: 10.0.0
  - name: community.crypto
    version: 3.0.5
  - name: community.docker
    version: 5.0.0
  - name: community.general
    version: 12.0.0
  - name: community.hashi_vault
    version: 7.1.0
  - name: community.library_inventory_filtering_v1
    version: 1.1.5
  - name: community.mysql
    version: 4.0.1
  - name: community.postgresql
    version: 4.1.0
  - name: community.proxmox
    version: 1.3.0
  - name: community.routeros
    version: 3.13.0
  - name: community.vmware
    version: 5.10.0
  - name: community.windows
    version: 3.0.1
  - name: fortinet.fortios
    version: 2.4.2
  - name: kubernetes.core
    version: 5.1.0
  - name: linode.cloud
    version: 0.41.1
  - name: microsoft.ad
    version: 1.9.2
  - name: microsoft.iis
    version: 1.0.3
  - name: microsoft.sql
    version: 2.6.4
  - name: openstack.cloud
    version: 2.4.1
  - name: paloaltonetworks.panos
    version: 3.2.0
  - name: vmware.vmware_rest
    version: 4.9.0
  - name: vmware.vmware
    version: 2.4.0
  - name: vyos.vyos
    version: 5.0.0
  - name: https://github.com/vmware/ansible-for-nsxt.git
    type: git
