---
- name: Hurling boulders...
  hosts: all
  serial: "{{ playbook_serial_number | default('100%') }}"
  gather_facts: false
  strategy: ansible.builtin.host_pinned

  pre_tasks:
    # - ansible.builtin.debug: msg="{{  }}" # Uncomment to debug variables
    - name: Getting the time...
      ansible.builtin.setup:
        filter: "*_time"
      delegate_to: localhost
      when: (deploy_mode == 'deploy') or (deploy_mode == 'redeploy')

  module_defaults:
    # Module defaults for https://docs.ansible.com/ansible/latest/collections/community/vmware/index.html#modules
    group/vmware: "{{ vmware_defaults | default(omit) }}"

    # vmware.vmware_rest uses different format module defaults and doesn't have a group
    # https://github.com/ansible-collections/vmware.vmware_rest/issues/361
    vmware.vmware_rest.vcenter_network_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_guest_identity_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_guest_networking_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_guest_networking_interfaces_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_guest_operations_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_guest_power_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_guest_power: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_hardware_ethernet_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_hardware_ethernet: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_power: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_tools_info: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm_tools: "{{ vmware_rest_defaults | default(omit) }}"
    vmware.vmware_rest.vcenter_vm: "{{ vmware_rest_defaults | default(omit) }}"

    # Module defaults for:
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/index.html#modules
    # https://docs.ansible.com/ansible/latest/collections/community/aws/index.html#modules
    group/aws: "{{ aws_defaults | default(omit) }}"

    # Module defaults for:
    # https://docs.ansible.com/ansible/latest/collections/azure/azcollection/index.html#plugins-in-azure-azcollection
    # Refer to link below for different naming reason
    # https://github.com/ansible-collections/azure/issues/977
    group/azure.azcollection.all: "{{ azure_defaults | default(omit) }}"

  roles:
    - role: nova.core.deploy_vars # Including deployment variables

    # Define -e pre_vm=role_name with the deploy alias to run the role and stop the play, the role must be able to run on localhost
    - role: nova.core.customization_pre_role
      when: pre_role is defined

    # Saving account's passwords to Vault
    - role: nova.core.secrets_to_vault
      when:
        - save_secrets_to_vault # Requires a running HashiCorp Vault server with LDAP auth enabled
        - not role_only # Only deploys configuration under roles/vm/role_name and stops
        - not role_only_wp # wp means with pre/post_vm_role
        - not deploy_mode == 'undeploy' # No need to save secrets when undeploying

    - role: nova.core.machine_operations # Creating (usually a virtual machine)

    - role: nova.core.configure_networking # Configuring VM networking

    - role: nova.core.connection # Setting correct network connection parameters

    # Define -e single_role=role_name with the deploy alias run the role and stop the play, useful for testing/development
    - role: nova.core.customization_single_role
      become: "{{ default_ansible_become | default(omit) }}"
      become_user: "{{ default_ansible_become_user | default(omit) }}"
      when: single_role is defined

    - role: nova.core.accounts # Creating required accounts
      become: "{{ default_ansible_become | default(omit) }}"
      become_user: "{{ default_ansible_become_user | default(omit) }}"
      when:
        - not role_only # Only deploys configuration under roles/vm/role_name and stops
        - not role_only_wp # wp means with pre/post_vm_role

    - role: nova.core.template_os_configuration # Used for configuring project or env specific templates
      become: "{{ default_ansible_become | default(omit) }}"
      become_user: "{{ default_ansible_become_user | default(omit) }}"
      when: template

    - role: nova.core.os_configuration # Running OS specific configurations
      become: "{{ default_ansible_become | default(omit) }}"
      become_user: "{{ default_ansible_become_user | default(omit) }}"
      when:
        - "'zone_local' not in group_names" # To avoid configuration for your own laptop
        - not role_only # Only deploys configuration under roles/vm/role_name and stops
        - not role_only_wp # wp means with pre/post_vm_role

    - role: nova.core.customization_pre_vm_role # Including pre_customization role if it exists
      become: "{{ default_ansible_become | default(omit) }}"
      become_user: "{{ default_ansible_become_user | default(omit) }}"
      when:
        - not role_only

    - role: nova.core.customization # Including machine specific role if exists
      become: "{{ default_ansible_become | default(omit) }}"
      become_user: "{{ default_ansible_become_user | default(omit) }}"

    - role: nova.core.customization_post_vm_role # Including post_customization specific role if exists
      become: "{{ default_ansible_become | default(omit) }}"
      become_user: "{{ default_ansible_become_user | default(omit) }}"
      when:
        - not role_only

    - role: nova.core.finalize # Running final & cleanup tasks
      become: "{{ default_ansible_become | default(omit) }}"
      become_user: "{{ default_ansible_become_user | default(omit) }}"

    - role: nova.core.get_ip
