---
name: ${CONTAINER_PROJECT_NAME}
services:
  catapult:
    tty: true
    image: ${IMAGE_FULL}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    network_mode: host
    restart: no
    volumes:
      - ${ROOT_DIR}/:/srv/
      - ${ROOT_DIR}/container/docker-entrypoint.sh:/docker-entrypoint.sh
      - ${ROOT_DIR}/container/home/builder/.ssh/:/home/builder/.ssh/
      - ${ROOT_DIR}/container/home/builder/.history:/home/builder/.history
      - ${ROOT_DIR}/container/home/builder/.zshrc:/home/builder/.zshrc
      - ${ROOT_DIR}/container/home/builder/.vault:/home/builder/.vault
      - ${HOST_SSH_AUTH_SOCK}:/ssh-agent
    environment:
      ALLOW_HOST_SSH_ACCESS: ${MAKEVAR_ALLOW_HOST_SSH_ACCESS}
      CATAPULT: 1 # This is used to check if the deployment is running in a Catapult container
      CONTAINER_GROUP_ID: ${CONTAINER_GROUP_ID}
      CONTAINER_GROUP_NAME: ${CONTAINER_GROUP_NAME}
      CONTAINER_USER_ID: ${CONTAINER_USER_ID}
      CONTAINER_USER_NAME: ${CONTAINER_USER_NAME}
      DISPLAY: ${DISPLAY}
      MAKEVAR_AUTO_UPDATE: ${MAKEVAR_AUTO_UPDATE}
      MAKEVAR_CATAPULT_VERSION: ${MAKEVAR_CATAPULT_VERSION}
      MAKEVAR_FREEZE_UPDATE: ${MAKEVAR_FREEZE_UPDATE}
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      SLACK_CHANNEL: ${MAKEVAR_WEBHOOK_CHANNEL}
      SLACK_USERNAME: ${MAKEVAR_WEBHOOK_USERNAME}
      SLACK_WEBHOOK_URL: ${MAKEVAR_WEBHOOK_URL}
      SSH_AUTH_SOCK: /ssh-agent
      TZ: ${MAKEVAR_TZ}
      USER: ${CONTAINER_USER_NAME}
    extra_hosts:
      - host.docker.internal:host-gateway
      - ${CONTAINER_NAME}:127.0.1.1
    logging:
      driver: json-file
      options:
        max-size: 250m
        max-file: "1"
