---
# Template created with packer
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_debian12

# vCenter Template name
vm_template: "{{ debian12_vm_template_name | default('catapult-template-debian12') }}"
