---
# Template created with packer
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_routeros7

vm_template: "{{ routeros7_vm_template_name | default('catapult-template-routeros7') }}"
