---
# Template created with packer
# Used only to create project templates from
base_vm_template: BASE_TEMPLATE_win81

vm_template: "{{ win81_vm_template_name | default('catapult-template-win81') }}"
