name: Catapult documentation builder

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/catapult-docs.yml
      - Readme.md
      - docs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Trigger Catapult Docs build
        run: |
          curl -XPOST -u "${{secrets.TOKEN_CATAPULT_DOCS_USERNAME}}:${{secrets.TOKEN_CATAPULT_DOCS}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" "https://api.github.com/repos/ClarifiedSecurity/catapult-docs/dispatches" --data '{"event_type": "build_docs_triggered_by_catapult"}'
