name: Catapult Docker image builder

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/docker-image.yml
      - Dockerfile
      - defaults/poetry.lock
      - defaults/pyproject.toml
      - defaults/requirements.yml
      - container/home/builder/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Pulling Catapult repository...
        uses: actions/checkout@v3

      - name: Preparing image build...
        run: make customizations

      - name: Logging into to GitHub Container Registry...
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Installing QEMU
        uses: docker/setup-qemu-action@v2

      - name: Building Catapult image...
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag ghcr.io/clarifiedsecurity/catapult:latest --platform linux/amd64,linux/arm64 --push .
