name: Catapult latest Docker image builder

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-image.yml
      - Dockerfile
      - scripts/general/install-docker-image**
      - defaults/requirements.yml
      - defaults/requirements.txt
      - container/home/builder/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Pulling Catapult repository...
        uses: actions/checkout@v4

      - name: Preparing image build...
        run: make customizations

      - name: Logging into to GitHub Container Registry...
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Installing QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Getting current version...
        run: |
          VERSION=$(cat version.yml | cut -d ' ' -f 2)
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Building Catapult image...
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          build-args: |
            VERSION=${{ env.IMAGE_VERSION }}
          push: true
          tags: |
            ghcr.io/clarifiedsecurity/catapult:latest
            ghcr.io/clarifiedsecurity/catapult:${{ env.IMAGE_VERSION }}
