name: Releasing a new version...

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  version_collection_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo...
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generating changelog contents...
        run: |
          TAG_NAME="v$(cat version.yml | cut -d " " -f2)"
          echo "LATEST_TAG=$TAG_NAME" >> $GITHUB_ENV

          # Creating temp changelog file
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^^)..HEAD > CHANGELOG.md

      - name: Generating a new release...
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.LATEST_TAG }}
          bodyFile: CHANGELOG.md
